/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import My_Code.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import static Interface.Login.idP;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import static Interface.Login.idP;

/**
 *
 * @author AAA
 */
public class Attendance extends javax.swing.JFrame {
   
    /**
     * Creates new form ResignedEmployeeList
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    String sql;
    String id;
    String re;
    int x;
    String date;
    String id1;
    String id2;
    String date1;
    String eid;
    int count;
    String l;
    String e;
    int ot;
    String time;
    String lt;
    int count1=0;
    
    public Attendance() {
             
        initComponents();
        
        con = DBconnect.connect();
        tableload ();
        
    }
    
    public void tableload () {
        
        try {
            
            sql = "SELECT `Employee_Id`, `Date`, `Enter_Time`, `Leave_Time`, `OT_Hours` FROM attendance";
            pst = con.prepareStatement ( sql );
            rs = pst.executeQuery ();
            
            attendance.setModel ( DbUtils.resultSetToTableModel ( rs ));
          
        } 
        
        catch ( Exception e ) {
            
            System.out.println ( e );
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        attendance = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        din = new javax.swing.JLabel();
        dout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(206, 196, 217));
        jPanel1.setAlignmentX(50.0F);

        jPanel2.setBackground(new java.awt.Color(85, 55, 118));

        Back.setBackground(new java.awt.Color(85, 55, 118));
        Back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.setAutoscrolls(true);
        Back.setBorder(null);
        Back.setBorderPainted(false);
        Back.setFocusable(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(85, 55, 118));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setAutoscrolls(true);
        Logout.setBorder(null);
        Logout.setBorderPainted(false);
        Logout.setFocusable(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Attendance");

        attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee_Id", "Name", "NIC", "Address", "Contact Number", "Designation"
            }
        ));
        attendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(attendance);

        jButton1.setBackground(new java.awt.Color(85, 55, 118));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Duty In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(85, 55, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Duty Off");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(din, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(dout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(din, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(dout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed

        this.dispose ();

    }//GEN-LAST:event_BackActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        Home_Page1 HP1 = new Home_Page1 ();
        Home_Page2 HP2 = new Home_Page2 ();
        HP1.setVisible ( true );
        this.dispose ();
        HP2.dispose ();

    }//GEN-LAST:event_LogoutActionPerformed

    private void attendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_attendanceMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date d = new Date ();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String da = sdf.format(d);
          
        try{
            String sql2 = "Select Id from employee where Username = '"+ idP +"'";
        pst = con.prepareStatement ( sql2 );
        rs = pst.executeQuery ();
          
        while(rs.next()){
            eid = rs.getString(1);
            
        }
            
        String sql = "Select Date from attendance where Employee_Id='"+ eid +"'";
        pst = con.prepareStatement ( sql );
        rs = pst.executeQuery ();
         
        while(rs.next()){
            date = rs.getString(1);
            //id1 = rs.getString(2);
            System.out.println(date);
            if((!date.equals(da))){
        count=0;
        
        date1=date;
        
        System.out.println("cd");
        
        
        
        String [] dateParts = da.split("-");
        String month1 = dateParts[1];
        String month12 = null;
        int num = Integer.parseInt(month1);
        switch (num)
        {
        case 1:
            month12 = "January";
            break;
        case 2:
            month12 = "February";
            break;
        case 3:
            month12 = "March";
            break;
        case 4:
            month12 = "April";
            break;
        case 5:
            month12 = "May";
            break;
        case 6:
            month12 = "June";
            break;
        case 7:
            month12 = "July";
            break;
        case 8:
            month12 = "August";
            break;
        case 9:
            month12 = "September";
            break;
        case 10:
            month12 = "October";
            break;
        case 11:
            month12 = "November";
            break;
        case 12:
            month12 = "December";
            break;
        
        }
        System.out.println(d);
        //System.out.println(LocalDateTime.now().getHour());
        
        
        
        int hour = (LocalDateTime.now().getHour());
        System.out.println(Integer.toString(hour));
        
        int minutes = (LocalDateTime.now().getMinute());
        System.out.println(Integer.toString(minutes));
      
        din.setText(Integer.toString(hour).concat(":").concat(Integer.toString(minutes)));
        
        System.out.println(date1);
        System.out.println(da);
        System.out.println(eid);
        //System.out.println(id1);
        
        String din1 = din.getText();
        
            if(jButton1.isEnabled()){
            count++;
            
        }
            if(count<=1){
            String sql1 = "Insert into attendance (`Employee_Id`, `Date`, `Month`, `Enter_Time`,`Leave_Time`, `OT_Hours`) values ('"+ eid +"','"+ da +"','"+ month12 +"','"+ din1 +"','0','0')";
            pst = con.prepareStatement ( sql1 );
            pst.execute();
            tableload();
        }
             
            
            }
        }
        }
        catch(Exception e){
            din.setText("");
             JOptionPane.showMessageDialog ( null, "You have already made your attendance" );
                
        }
        //if(date)
        //if(jButton1.isEnabled())
        
        /*Calendar rightNow = Calendar.getInstance();
        int hour = rightNow.get(Calendar.HOUR_OF_DAY);
        System.out.println(Integer.toString(hour));*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        Date d = new Date ();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String da = sdf.format(d);
        
        try{
            String sql2 = "Select Id from employee where Username = '"+ idP +"'";
        pst = con.prepareStatement ( sql2 );
        rs = pst.executeQuery ();
          
        while(rs.next()){
            eid = rs.getString(1);
            
        }
         /*String sql1 = "Select Enter_Time from attendance where Employee_Id='"+ eid +"' and Date='"+ da +"'";
        pst = con.prepareStatement ( sql1 );
        rs = pst.executeQuery ();   */ 
        
        /*while(rs.next()){
            time = rs.getString(1);
        }*/
            //System.out.println(time);
            //if(time!=null){
                
            
        String sql = "Select Date,Employee_Id,Leave_Time from attendance where Employee_Id='"+ eid +"'";
        pst = con.prepareStatement ( sql );
        rs = pst.executeQuery ();
       
        while(rs.next()){
            date = rs.getString(1);
            id2 = rs.getString(2);
            lt = rs.getString(3);
            System.out.println(date);
            String r = "00:00:00";
            if(date.equals(da)){
                //int count1 = 0;
                ///String sql1 = "Select Leave_Time from attendance where Employee_Id='"+ eid +"' and Date='"+da+"'";
        //pst = con.prepareStatement ( sql1 );
        //rs = pst.executeQuery ();
        //while(rs.next()){
        //System.out.println(rs.getString(1));
        //}
        //System.out.println(LocalDateTime.now().getHour());
        int hour = (LocalDateTime.now().getHour());
        System.out.println(Integer.toString(hour));
        
        int minutes = (LocalDateTime.now().getMinute());
        System.out.println(Integer.toString(minutes));
      
        dout.setText(Integer.toString(hour).concat(":").concat(Integer.toString(minutes)));
        
        String dout1 = dout.getText();
        
        
            /*if(jButton2.isEnabled()){
            count1++;
            
        }*/
            if(lt.equals(r)){
                
                String sql3 = "Update attendance set Leave_Time='"+ dout1 +"' where Date='"+ da +"' and Employee_Id='"+ eid +"' ";
                pst = con.prepareStatement ( sql3 );
                pst.execute ();
                
                String sql21 = "Select Enter_Time,Leave_Time from attendance where Date='"+ da +"' and Employee_Id='"+ eid +"'";
                pst = con.prepareStatement ( sql21 );
                rs = pst.executeQuery ();
                
                while(rs.next()){
                    e = rs.getString(1);
                    l = rs.getString(2);
                }
                
                SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
                Date date1 = format.parse(e);
                Date date2 = format.parse(l);
                System.out.println("kk");
                long difference = date2.getTime()- date1.getTime(); 
                
                System.out.println(difference);
                long diffHours = difference / (60 * 60 * 1000); 
                
                if(diffHours==0){
                    ot = 0;
                }
                else if(diffHours>8){
                    String ot1 = String.valueOf(diffHours);
                    ot = Integer.parseInt(ot1)-8;
                }
                else if(diffHours<8){
                    String ot1 = String.valueOf(diffHours);
                    ot = Integer.parseInt(ot1)-8;
                }
                System.out.println(ot);
                String sql5 = "Update attendance set OT_Hours='"+ ot +"' where Date='"+ da +"' and Employee_Id='"+ eid +"' ";
                pst = con.prepareStatement ( sql5 );
                pst.execute ();
                tableload();
            }
            else{
                dout.setText("");
             JOptionPane.showMessageDialog ( null, "You have already made your attendance" );
                }
            }
            }}
        /*else{
                dout.setText("");
             JOptionPane.showMessageDialog ( null, "Your Work in time not marked" );
                
                }}}*/
        catch(Exception e){
            dout.setText("");
             JOptionPane.showMessageDialog ( null, "Your Work in time not marked" );
                
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Logout;
    private javax.swing.JTable attendance;
    private javax.swing.JLabel din;
    private javax.swing.JLabel dout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
